version: '3.8'

services:
  data-service:
    image: localhost:5000/stock-forecast-data-service:1.0.0
    ports:
      - "5000:5000"
    restart: always

  backend:
    image: localhost:5000/stock-forecast-backend:1.0.0
    ports:
      - "8080:8080"
    environment:
      - PYTHON_SERVICE_URL=http://data-service:5000
    env_file:
      - .env
    depends_on:
      - data-service
    restart: always
