version: '3.8'

services:
  backend:
    container_name: stock-forecast-backend
    image: localhost:5000/stock-forecast-backend:1.0.0
    ports:
      - "127.0.0.1:8080:8080"  # 只绑定本地，由nginx代理
    env_file:
      - .env
    restart: always
    networks:
      - stock-network

networks:
  stock-network:
    external: true
    name: stock-forecast-network
